### ISSUE TITLE
how to use this board?

### ISSUE THREAD

**Issue by namoaton** [TheLongRunSmoke/UniHabu#1]
Hello.
How to use this board?

**Comment by TheLongRunSmoke** [comment]
Hi. 
Like any outhers MPSSE supported board with FTDI chips. It's provide 4 UART or RS232, for beginning, and any other interfaces with proper PC software. Just google "interface name mpsse".
And...there are examples on FTDI site. You can write you own implementation.
E.g. I wrote a controller of MIL-STD-1553, few years ago.

**Comment by namoaton** [comment]
ok thanks. I have this board, and think how to use it. now it is clear

**Comment by TheLongRunSmoke** [comment]
Am...what? Do you have "that" board or something similar on FT4232?

**Comment by namoaton** [comment]
I have this, not similar.  Именно эта платка. купил в китае на али

**Comment by TheLongRunSmoke** [comment]
Ссылка?

**Comment by namoaton** [comment]
[https://ru.aliexpress.com/wholesale?catId=0&initiative_id=SB_20170920091645&isPremium=y&SearchText=ft2232hl](url)

**Comment by TheLongRunSmoke** [comment]
Во-первых, там FT**2**232 поэтому работают только два порта из четырёх и только один поддерживает MPSSE.
Во-вторых, если будут проблемы, замени С4 на тантал 4мкФ или больше, я его не зря туда ставил, и припаяй снизу перемычку размера 1206, если её нет.

**Comment by namoaton** [comment]
хорошо. спасибо буду мучать. буду под питон пробовать
